#!/bin/sh

# SSH access configuration: ensure password auth is enabled by default.
uci set dropbear.@dropbear[0].PasswordAuth='on'
uci set dropbear.@dropbear[0].RootPasswordAuth='on'
uci commit dropbear 2>/dev/null

# Enable 32MB ZRAM Swap with ultra-fast lz4 compression on 64MB RAM SoC
if [ -e /dev/zram0 ]; then
    echo lz4 > /sys/block/zram0/comp_algorithm 2>/dev/null || echo lzo-rle > /sys/block/zram0/comp_algorithm 2>/dev/null
    zram_size=$((32 * 1024 * 1024))
    echo $zram_size > /sys/block/zram0/disksize 2>/dev/null
    mkswap /dev/zram0 2>/dev/null
    swapon -p 100 /dev/zram0 2>/dev/null
fi

# Firewall rules for HTTP API (80) & MQTT (1883)
uci add firewall rule 2>/dev/null
uci set firewall.@rule[-1].name='Allow-HTTP-API' 2>/dev/null
uci set firewall.@rule[-1].src='*' 2>/dev/null
uci set firewall.@rule[-1].proto='tcp' 2>/dev/null
uci set firewall.@rule[-1].dest_port='80' 2>/dev/null
uci set firewall.@rule[-1].target='ACCEPT' 2>/dev/null

uci add firewall rule 2>/dev/null
uci set firewall.@rule[-1].name='Allow-MQTT' 2>/dev/null
uci set firewall.@rule[-1].src='*' 2>/dev/null
uci set firewall.@rule[-1].proto='tcp' 2>/dev/null
uci set firewall.@rule[-1].dest_port='1883' 2>/dev/null
uci set firewall.@rule[-1].target='ACCEPT' 2>/dev/null

uci commit firewall 2>/dev/null

exit 0
