#!/bin/sh /etc/rc.common
# Baresip VoIP daemon init script

START=95
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/baresip
    procd_append_param command -f /etc/baresip
    # Run in background with no stdin
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
