general =
{
    name = "Audio Pro C3";
    output_backend = "alsa";
    mdns_backend = "avahi";
    port = 5000;
    interpolation = "basic";
};

alsa =
{
    output_device = "airplay_in";
    mixer_control_name = "Master";
    output_format = "S16";
    output_rate = 44100;
    # 6615 frames = standard 150ms buffer @ 44.1kHz (customizable down to 1323/30ms or 441/10ms)
    audio_backend_buffer_desired_length = 6615;
    disable_synchronization = "no";
};

metadata =
{
    enabled = "yes";
    include_cover_art = "yes";
    pipe_name = "/tmp/shairport-sync-meta";
    socket_msec = 200;
};

